### ISSUE TITLE
GameObject::GetComponent causing unresolved external symbol

### ISSUE THREAD

**Issue by JmsPae** [JFrap/Engine-Alpha#4]
`2>Source.obj : error LNK2019: unresolved external symbol "public: class alpha::Component * __thiscall alpha::GameObject::GetComponent<class game::Player>(void)" (??$GetComponent@VPlayer@game@@@GameObject@alpha@@QAEPAVComponent@1@XZ) referenced in function "public: virtual void __thiscall MainScene::Init(void)" (?Init@MainScene@@UAEXXZ)
2>Tank.obj : error LNK2019: unresolved external symbol "public: class alpha::Component * __thiscall alpha::GameObject::GetComponent<class game::Tank>(void)" (??$GetComponent@VTank@game@@@GameObject@alpha@@QAEPAVComponent@1@XZ) referenced in function "protected: void __thiscall game::Tank::Fire(float)" (?Fire@Tank@game@@IAEXM@Z)
2>C:\Users\James\Documents\GitHub\Engine-Alpha\EngineAlpha\Debug\Example.exe : fatal error LNK1120: 2 unresolved externals
2>Done building project "Example.vcxproj" -- FAILED.`

Uncertain to why this is, but it started after adding cross-references between Scene and GamebObject, so its probably something to do with that.

Temporary fix implemented, would rather have it in cpp.

**Comment by ghost** [comment]
I hope you know that templates have to be implemented in the header :)

**Comment by JmsPae** [comment]
> I hope you know that templates have to be implemented in the header :)

Header definition looks like this

`template<class T>
Component* GetComponent();`

and the cpp definition looks like this

`template<class T>
Component *GameObject::GetComponent() {`
(not exactly like this (thanks, github) but you get the idea)

Maybe there's some sort of fuck-up there somewhere

**Comment by ghost** [comment]
But templates still need to always be completly in the header

**Comment by JmsPae** [comment]
> But templates still need to always be completly in the header

Well shit, i guess my fix will have to be permanent
